server:
  port: 9091
spring:
  datasource:
    username: sa
    password: null
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: INFO
    com.tekleads: DEBUG